### ISSUE TITLE
btw

### ISSUE THREAD

**Issue by manu1511** [mkwlf/dotfiles#1]
you use arch!

just sayin' 😊

**Comment by mkwlf** [comment]
@manu1511 - unfortunately I don't use arch anymore 😭  - work has turned me to the dark side of the 🍏 ... **ULTIMATE POWER** _runs docker and machine goes bang_ 🙄 

really miss arch (based) systems.

**Comment by manu1511** [comment]
how dare you! 🙀 so you're totally a soydev now? 😹

we might already know each other from vlbgwebdev then...  
so I'm looking for a job in the area, somewhat frontend/backend guy, can you recommend me something pls? 
not a 10x dev here, but also not an absolute beginner

**Comment by mkwlf** [comment]
@manu1511 I send you an email to your public gh mail address... can you reply?
